services:
  - type: web
    name: Gigpurse server
    runtime: go
    plan: free
    buildCommand: go build -o bin/gigpurse ./cmd/gigpurse
    startCommand: ./bin/gigpurse
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: gigpurse
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOW_ADMIN_SIGNUP
        value: "false"
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: MAILJET_API_KEY
        sync: false
      - key: MAILJET_API_SECRET
        sync: false
      - key: MAILJET_FROM_EMAIL
        sync: false
      - key: MAILJET_FROM_NAME
        value: Gigpurse
